
server:
  port: 8080
  ssl:
    enabled: false

spring:
  data:
    redis:
      repositories:
        enabled: false
  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: "jdbc:postgresql://localhost:5432/nbm"
    username: nbm
    password: